# -*- coding: utf-8 -*-
# Auto-generated from PokeAPI move_names.csv (919 moves)

MOVES_FR = {
    "Pound": "Écras’Face",
    "Karate Chop": "Poing Karaté",
    "Double Slap": "Torgnoles",
    "Comet Punch": "Poing Comète",
    "Mega Punch": "Ultimapoing",
    "Pay Day": "Jackpot",
    "Fire Punch": "Poing Feu",
    "Ice Punch": "Poing Glace",
    "Thunder Punch": "Poing Éclair",
    "Scratch": "Griffe",
    "Vise Grip": "Force Poigne",
    "Guillotine": "Guillotine",
    "Razor Wind": "Coupe-Vent",
    "Swords Dance": "Danse Lames",
    "Cut": "Coupe",
    "Gust": "Tornade",
    "Wing Attack": "Cru-Ailes",
    "Whirlwind": "Cyclone",
    "Fly": "Vol",
    "Bind": "Étreinte",
    "Slam": "Souplesse",
    "Vine Whip": "Fouet Lianes",
    "Stomp": "Écrasement",
    "Double Kick": "Double Pied",
    "Mega Kick": "Ultimawashi",
    "Jump Kick": "Pied Sauté",
    "Rolling Kick": "Mawashi Geri",
    "Sand Attack": "Jet de Sable",
    "Headbutt": "Coup d’Boule",
    "Horn Attack": "Koud’Korne",
    "Fury Attack": "Furie",
    "Horn Drill": "Empal’Korne",
    "Tackle": "Charge",
    "Body Slam": "Plaquage",
    "Wrap": "Ligotage",
    "Take Down": "Bélier",
    "Thrash": "Mania",
    "Double-Edge": "Damoclès",
    "Tail Whip": "Mimi-Queue",
    "Poison Sting": "Dard-Venin",
    "Twineedle": "Double Dard",
    "Pin Missile": "Dard-Nuée",
    "Leer": "Groz’Yeux",
    "Bite": "Morsure",
    "Growl": "Rugissement",
    "Roar": "Hurlement",
    "Sing": "Berceuse",
    "Supersonic": "Ultrason",
    "Sonic Boom": "Sonic Boom",
    "Disable": "Entrave",
    "Acid": "Acide",
    "Ember": "Flammèche",
    "Flamethrower": "Lance-Flammes",
    "Mist": "Brume",
    "Water Gun": "Pistolet à O",
    "Hydro Pump": "Hydrocanon",
    "Surf": "Surf",
    "Ice Beam": "Laser Glace",
    "Blizzard": "Blizzard",
    "Psybeam": "Rafale Psy",
    "Bubble Beam": "Bulles d’O",
    "Aurora Beam": "Onde Boréale",
    "Hyper Beam": "Ultralaser",
    "Peck": "Picpic",
    "Drill Peck": "Bec Vrille",
    "Submission": "Sacrifice",
    "Low Kick": "Balayage",
    "Counter": "Riposte",
    "Seismic Toss": "Frappe Atlas",
    "Strength": "Force",
    "Absorb": "Vole-Vie",
    "Mega Drain": "Méga-Sangsue",
    "Leech Seed": "Vampigraine",
    "Growth": "Croissance",
    "Razor Leaf": "Tranch’Herbe",
    "Solar Beam": "Lance-Soleil",
    "Poison Powder": "Poudre Toxik",
    "Stun Spore": "Para-Spore",
    "Sleep Powder": "Poudre Dodo",
    "Petal Dance": "Danse Fleurs",
    "String Shot": "Sécrétion",
    "Dragon Rage": "Draco-Rage",
    "Fire Spin": "Danse Flammes",
    "Thunder Shock": "Éclair",
    "Thunderbolt": "Tonnerre",
    "Thunder Wave": "Cage Éclair",
    "Thunder": "Fatal-Foudre",
    "Rock Throw": "Jet-Pierres",
    "Earthquake": "Séisme",
    "Fissure": "Abîme",
    "Dig": "Tunnel",
    "Toxic": "Toxik",
    "Confusion": "Choc Mental",
    "Psychic": "Psyko",
    "Hypnosis": "Hypnose",
    "Meditate": "Yoga",
    "Agility": "Hâte",
    "Quick Attack": "Vive-Attaque",
    "Rage": "Frénésie",
    "Teleport": "Téléport",
    "Night Shade": "Ombre Nocturne",
    "Mimic": "Copie",
    "Screech": "Grincement",
    "Double Team": "Reflet",
    "Recover": "Soin",
    "Harden": "Armure",
    "Minimize": "Lilliput",
    "Smokescreen": "Brouillard",
    "Confuse Ray": "Onde Folie",
    "Withdraw": "Repli",
    "Defense Curl": "Boul’Armure",
    "Barrier": "Bouclier",
    "Light Screen": "Mur Lumière",
    "Haze": "Buée Noire",
    "Reflect": "Protection",
    "Focus Energy": "Puissance",
    "Bide": "Patience",
    "Metronome": "Métronome",
    "Mirror Move": "Mimique",
    "Self-Destruct": "Destruction",
    "Egg Bomb": "Bombe Œuf",
    "Lick": "Léchouille",
    "Smog": "Purédpois",
    "Sludge": "Détritus",
    "Bone Club": "Massd’Os",
    "Fire Blast": "Déflagration",
    "Waterfall": "Cascade",
    "Clamp": "Claquoir",
    "Swift": "Météores",
    "Skull Bash": "Coud’Krâne",
    "Spike Cannon": "Picanon",
    "Constrict": "Constriction",
    "Amnesia": "Amnésie",
    "Kinesis": "Télékinésie",
    "Soft-Boiled": "E-Coque",
    "High Jump Kick": "Pied Voltige",
    "Glare": "Regard Médusant",
    "Dream Eater": "Dévorêve",
    "Poison Gas": "Gaz Toxik",
    "Barrage": "Pilonnage",
    "Leech Life": "Vampirisme",
    "Lovely Kiss": "Grobisou",
    "Sky Attack": "Piqué",
    "Transform": "Morphing",
    "Bubble": "Écume",
    "Dizzy Punch": "Uppercut",
    "Spore": "Spore",
    "Flash": "Flash",
    "Psywave": "Vague Psy",
    "Splash": "Trempette",
    "Acid Armor": "Acidarmure",
    "Crabhammer": "Pince-Masse",
    "Explosion": "Explosion",
    "Fury Swipes": "Combo-Griffe",
    "Bonemerang": "Osmerang",
    "Rest": "Repos",
    "Rock Slide": "Éboulement",
    "Hyper Fang": "Croc de Mort",
    "Sharpen": "Affûtage",
    "Conversion": "Conversion",
    "Tri Attack": "Triplattaque",
    "Super Fang": "Croc Fatal",
    "Slash": "Tranche",
    "Substitute": "Clonage",
    "Struggle": "Lutte",
    "Sketch": "Gribouille",
    "Triple Kick": "Triple Pied",
    "Thief": "Larcin",
    "Spider Web": "Toile",
    "Mind Reader": "Lire-Esprit",
    "Nightmare": "Cauchemar",
    "Flame Wheel": "Roue de Feu",
    "Snore": "Ronflement",
    "Curse": "Malédiction",
    "Flail": "Gigotage",
    "Conversion 2": "Conversion 2",
    "Aeroblast": "Aéroblast",
    "Cotton Spore": "Spore Coton",
    "Reversal": "Contre",
    "Spite": "Dépit",
    "Powder Snow": "Poudreuse",
    "Protect": "Abri",
    "Mach Punch": "Mach Punch",
    "Scary Face": "Grimace",
    "Feint Attack": "Feinte",
    "Sweet Kiss": "Doux Baiser",
    "Belly Drum": "Cognobidon",
    "Sludge Bomb": "Bombe Beurk",
    "Mud-Slap": "Coud’Boue",
    "Octazooka": "Octazooka",
    "Spikes": "Picots",
    "Zap Cannon": "Élecanon",
    "Foresight": "Clairvoyance",
    "Destiny Bond": "Lien du Destin",
    "Perish Song": "Requiem",
    "Icy Wind": "Vent Glace",
    "Detect": "Détection",
    "Bone Rush": "Charge Os",
    "Lock-On": "Verrouillage",
    "Outrage": "Colère",
    "Sandstorm": "Tempête de Sable",
    "Giga Drain": "Giga-Sangsue",
    "Endure": "Ténacité",
    "Charm": "Charme",
    "Rollout": "Roulade",
    "False Swipe": "Faux-Chage",
    "Swagger": "Vantardise",
    "Milk Drink": "Lait à Boire",
    "Spark": "Étincelle",
    "Fury Cutter": "Taillade",
    "Steel Wing": "Ailes d’Acier",
    "Mean Look": "Regard Noir",
    "Attract": "Attraction",
    "Sleep Talk": "Blabla Dodo",
    "Heal Bell": "Glas de Soin",
    "Return": "Retour",
    "Present": "Cadeau",
    "Frustration": "Frustration",
    "Safeguard": "Rune Protect",
    "Pain Split": "Balance",
    "Sacred Fire": "Feu Sacré",
    "Magnitude": "Ampleur",
    "Dynamic Punch": "Dynamo-Poing",
    "Megahorn": "Mégacorne",
    "Dragon Breath": "Draco-Souffle",
    "Baton Pass": "Relais",
    "Encore": "Encore",
    "Pursuit": "Poursuite",
    "Rapid Spin": "Tour Rapide",
    "Sweet Scent": "Doux Parfum",
    "Iron Tail": "Queue de Fer",
    "Metal Claw": "Griffe Acier",
    "Vital Throw": "Corps Perdu",
    "Morning Sun": "Aurore",
    "Synthesis": "Synthèse",
    "Moonlight": "Rayon Lune",
    "Hidden Power": "Puissance Cachée",
    "Cross Chop": "Coup Croix",
    "Twister": "Ouragan",
    "Rain Dance": "Danse Pluie",
    "Sunny Day": "Zénith",
    "Crunch": "Mâchouille",
    "Mirror Coat": "Voile Miroir",
    "Psych Up": "Boost",
    "Extreme Speed": "Vitesse Extrême",
    "Ancient Power": "Pouvoir Antique",
    "Shadow Ball": "Ball’Ombre",
    "Future Sight": "Prescience",
    "Rock Smash": "Éclate-Roc",
    "Whirlpool": "Siphon",
    "Beat Up": "Baston",
    "Fake Out": "Bluff",
    "Uproar": "Brouhaha",
    "Stockpile": "Stockage",
    "Spit Up": "Relâche",
    "Swallow": "Avale",
    "Heat Wave": "Canicule",
    "Hail": "Grêle",
    "Torment": "Tourmente",
    "Flatter": "Flatterie",
    "Will-O-Wisp": "Feu Follet",
    "Memento": "Souvenir",
    "Facade": "Façade",
    "Focus Punch": "Mitra-Poing",
    "Smelling Salts": "Stimulant",
    "Follow Me": "Par Ici",
    "Nature Power": "Force Nature",
    "Charge": "Chargeur",
    "Taunt": "Provoc",
    "Helping Hand": "Coup d’Main",
    "Trick": "Tour de Magie",
    "Role Play": "Imitation",
    "Wish": "Vœu",
    "Assist": "Assistance",
    "Ingrain": "Racines",
    "Superpower": "Surpuissance",
    "Magic Coat": "Reflet Magik",
    "Recycle": "Recyclage",
    "Revenge": "Vendetta",
    "Brick Break": "Casse-Brique",
    "Yawn": "Bâillement",
    "Knock Off": "Sabotage",
    "Endeavor": "Effort",
    "Eruption": "Éruption",
    "Skill Swap": "Échange",
    "Imprison": "Possessif",
    "Refresh": "Régénération",
    "Grudge": "Rancune",
    "Snatch": "Saisie",
    "Secret Power": "Force Cachée",
    "Dive": "Plongée",
    "Arm Thrust": "Cogne",
    "Camouflage": "Camouflage",
    "Tail Glow": "Lumi-Queue",
    "Luster Purge": "Lumi-Éclat",
    "Mist Ball": "Ball’Brume",
    "Feather Dance": "Danse Plumes",
    "Teeter Dance": "Danse Folle",
    "Blaze Kick": "Pied Brûleur",
    "Mud Sport": "Lance-Boue",
    "Ice Ball": "Ball’Glace",
    "Needle Arm": "Poing Dard",
    "Slack Off": "Paresse",
    "Hyper Voice": "Mégaphone",
    "Poison Fang": "Crochet Venin",
    "Crush Claw": "Éclate Griffe",
    "Blast Burn": "Rafale Feu",
    "Hydro Cannon": "Hydroblast",
    "Meteor Mash": "Poing Météore",
    "Astonish": "Étonnement",
    "Weather Ball": "Ball’Météo",
    "Aromatherapy": "Aromathérapie",
    "Fake Tears": "Croco Larme",
    "Air Cutter": "Tranch’Air",
    "Overheat": "Surchauffe",
    "Odor Sleuth": "Flair",
    "Rock Tomb": "Tomberoche",
    "Silver Wind": "Vent Argenté",
    "Metal Sound": "Strido-Son",
    "Grass Whistle": "Siffl’Herbe",
    "Tickle": "Chatouille",
    "Cosmic Power": "Force Cosmique",
    "Water Spout": "Giclédo",
    "Signal Beam": "Rayon Signal",
    "Shadow Punch": "Poing Ombre",
    "Extrasensory": "Extrasenseur",
    "Sky Uppercut": "Stratopercut",
    "Sand Tomb": "Tourbi-Sable",
    "Sheer Cold": "Glaciation",
    "Muddy Water": "Ocroupi",
    "Bullet Seed": "Balle Graine",
    "Aerial Ace": "Aéropique",
    "Icicle Spear": "Stalactite",
    "Iron Defense": "Mur de Fer",
    "Block": "Barrage",
    "Howl": "Grondement",
    "Dragon Claw": "Draco-Griffe",
    "Frenzy Plant": "Végé-Attaque",
    "Bulk Up": "Gonflette",
    "Bounce": "Rebond",
    "Mud Shot": "Tir de Boue",
    "Poison Tail": "Queue-Poison",
    "Covet": "Implore",
    "Volt Tackle": "Électacle",
    "Magical Leaf": "Feuille Magik",
    "Water Sport": "Tourniquet",
    "Calm Mind": "Plénitude",
    "Leaf Blade": "Lame Feuille",
    "Dragon Dance": "Danse Draco",
    "Rock Blast": "Boule Roc",
    "Shock Wave": "Onde de Choc",
    "Water Pulse": "Vibraqua",
    "Doom Desire": "Vœu Destructeur",
    "Psycho Boost": "Psycho-Boost",
    "Roost": "Atterrissage",
    "Gravity": "Gravité",
    "Miracle Eye": "Œil Miracle",
    "Wake-Up Slap": "Réveil Forcé",
    "Hammer Arm": "Marto-Poing",
    "Gyro Ball": "Gyroballe",
    "Healing Wish": "Vœu Soin",
    "Brine": "Saumure",
    "Natural Gift": "Don Naturel",
    "Feint": "Ruse",
    "Pluck": "Picore",
    "Tailwind": "Vent Arrière",
    "Acupressure": "Acupression",
    "Metal Burst": "Fulmifer",
    "U-turn": "Demi-Tour",
    "Close Combat": "Close Combat",
    "Payback": "Représailles",
    "Assurance": "Assurance",
    "Embargo": "Embargo",
    "Fling": "Dégommage",
    "Psycho Shift": "Échange Psy",
    "Trump Card": "Atout",
    "Heal Block": "Anti-Soin",
    "Wring Out": "Essorage",
    "Power Trick": "Astuce Force",
    "Gastro Acid": "Suc Digestif",
    "Lucky Chant": "Air Veinard",
    "Me First": "Moi d’Abord",
    "Copycat": "Photocopie",
    "Power Swap": "Permuforce",
    "Guard Swap": "Permugarde",
    "Punishment": "Punition",
    "Last Resort": "Dernier Recours",
    "Worry Seed": "Soucigraine",
    "Sucker Punch": "Coup Bas",
    "Toxic Spikes": "Pics Toxik",
    "Heart Swap": "Permucœur",
    "Aqua Ring": "Anneau Hydro",
    "Magnet Rise": "Vol Magnétik",
    "Flare Blitz": "Boutefeu",
    "Force Palm": "Forte-Paume",
    "Aura Sphere": "Aurasphère",
    "Rock Polish": "Poliroche",
    "Poison Jab": "Direct Toxik",
    "Dark Pulse": "Vibrobscur",
    "Night Slash": "Tranche-Nuit",
    "Aqua Tail": "Hydro-Queue",
    "Seed Bomb": "Canon Graine",
    "Air Slash": "Lame d’Air",
    "X-Scissor": "Plaie Croix",
    "Bug Buzz": "Bourdon",
    "Dragon Pulse": "Draco-Choc",
    "Dragon Rush": "Draco-Charge",
    "Power Gem": "Rayon Gemme",
    "Drain Punch": "Vampi-Poing",
    "Vacuum Wave": "Onde Vide",
    "Focus Blast": "Exploforce",
    "Energy Ball": "Éco-Sphère",
    "Brave Bird": "Rapace",
    "Earth Power": "Telluriforce",
    "Switcheroo": "Passe-Passe",
    "Giga Impact": "Giga Impact",
    "Nasty Plot": "Machination",
    "Bullet Punch": "Pisto-Poing",
    "Avalanche": "Avalanche",
    "Ice Shard": "Éclats Glace",
    "Shadow Claw": "Griffe Ombre",
    "Thunder Fang": "Crocs Éclair",
    "Ice Fang": "Crocs Givre",
    "Fire Fang": "Crocs Feu",
    "Shadow Sneak": "Ombre Portée",
    "Mud Bomb": "Boue-Bombe",
    "Psycho Cut": "Coupe Psycho",
    "Zen Headbutt": "Psykoud’Boul",
    "Mirror Shot": "Miroi-Tir",
    "Flash Cannon": "Luminocanon",
    "Rock Climb": "Escalade",
    "Defog": "Anti-Brume",
    "Trick Room": "Distorsion",
    "Draco Meteor": "Draco-Météore",
    "Discharge": "Coup d’Jus",
    "Lava Plume": "Ébullilave",
    "Leaf Storm": "Tempête Verte",
    "Power Whip": "Mégafouet",
    "Rock Wrecker": "Roc-Boulet",
    "Cross Poison": "Poison Croix",
    "Gunk Shot": "Détricanon",
    "Iron Head": "Tête de Fer",
    "Magnet Bomb": "Bombe Aimant",
    "Stone Edge": "Lame de Roc",
    "Captivate": "Séduction",
    "Stealth Rock": "Piège de Roc",
    "Grass Knot": "Nœud Herbe",
    "Chatter": "Babil",
    "Judgment": "Jugement",
    "Bug Bite": "Piqûre",
    "Charge Beam": "Rayon Chargé",
    "Wood Hammer": "Martobois",
    "Aqua Jet": "Aqua-Jet",
    "Attack Order": "Appel Attaque",
    "Defend Order": "Appel Défense",
    "Heal Order": "Appel Soins",
    "Head Smash": "Fracass’Tête",
    "Double Hit": "Coup Double",
    "Roar of Time": "Hurle-Temps",
    "Spacial Rend": "Spatio-Rift",
    "Lunar Dance": "Danse Lune",
    "Crush Grip": "Presse",
    "Magma Storm": "Vortex Magma",
    "Dark Void": "Trou Noir",
    "Seed Flare": "Fulmigraine",
    "Ominous Wind": "Vent Mauvais",
    "Shadow Force": "Revenant",
    "Hone Claws": "Aiguisage",
    "Wide Guard": "Garde Large",
    "Guard Split": "Partage Garde",
    "Power Split": "Partage Force",
    "Wonder Room": "Zone Étrange",
    "Psyshock": "Choc Psy",
    "Venoshock": "Choc Venin",
    "Autotomize": "Allègement",
    "Rage Powder": "Poudre Fureur",
    "Telekinesis": "Lévikinésie",
    "Magic Room": "Zone Magique",
    "Smack Down": "Anti-Air",
    "Storm Throw": "Yama Arashi",
    "Flame Burst": "Rebondifeu",
    "Sludge Wave": "Cradovague",
    "Quiver Dance": "Papillodanse",
    "Heavy Slam": "Tacle Lourd",
    "Synchronoise": "Synchropeine",
    "Electro Ball": "Boule Élek",
    "Soak": "Détrempage",
    "Flame Charge": "Nitrocharge",
    "Coil": "Enroulement",
    "Low Sweep": "Balayette",
    "Acid Spray": "Bombe Acide",
    "Foul Play": "Tricherie",
    "Simple Beam": "Rayon Simple",
    "Entrainment": "Ten-Danse",
    "After You": "Après Vous",
    "Round": "Chant Canon",
    "Echoed Voice": "Écho",
    "Chip Away": "Attrition",
    "Clear Smog": "Bain de Smog",
    "Stored Power": "Force Ajoutée",
    "Quick Guard": "Prévention",
    "Ally Switch": "Interversion",
    "Scald": "Ébullition",
    "Shell Smash": "Exuviation",
    "Heal Pulse": "Vibra Soin",
    "Hex": "Châtiment",
    "Sky Drop": "Chute Libre",
    "Shift Gear": "Chgt Vitesse",
    "Circle Throw": "Projection",
    "Incinerate": "Calcination",
    "Quash": "À la Queue",
    "Acrobatics": "Acrobatie",
    "Reflect Type": "Copie-Type",
    "Retaliate": "Vengeance",
    "Final Gambit": "Tout ou Rien",
    "Bestow": "Passe-Cadeau",
    "Inferno": "Feu d’Enfer",
    "Water Pledge": "Aire d’Eau",
    "Fire Pledge": "Aire de Feu",
    "Grass Pledge": "Aire d’Herbe",
    "Volt Switch": "Change Éclair",
    "Struggle Bug": "Survinsecte",
    "Bulldoze": "Piétisol",
    "Frost Breath": "Souffle Glacé",
    "Dragon Tail": "Draco-Queue",
    "Work Up": "Rengorgement",
    "Electroweb": "Toile Élek",
    "Wild Charge": "Éclair Fou",
    "Drill Run": "Tunnelier",
    "Dual Chop": "Double Baffe",
    "Heart Stamp": "Crève-Cœur",
    "Horn Leech": "Encornebois",
    "Sacred Sword": "Lame Sainte",
    "Razor Shell": "Coqui-Lame",
    "Heat Crash": "Tacle Feu",
    "Leaf Tornado": "Phytomixeur",
    "Steamroller": "Bulldoboule",
    "Cotton Guard": "Cotogarde",
    "Night Daze": "Explonuit",
    "Psystrike": "Frappe Psy",
    "Tail Slap": "Plumo-Queue",
    "Hurricane": "Vent Violent",
    "Head Charge": "Peignée",
    "Gear Grind": "Lancécrou",
    "Searing Shot": "Incendie",
    "Techno Blast": "Techno-Buster",
    "Relic Song": "Chant Antique",
    "Secret Sword": "Lame Ointe",
    "Glaciate": "Ère Glaciaire",
    "Bolt Strike": "Charge Foudre",
    "Blue Flare": "Flamme Bleue",
    "Fiery Dance": "Danse du Feu",
    "Freeze Shock": "Éclair Gelé",
    "Ice Burn": "Feu Glacé",
    "Snarl": "Aboiement",
    "Icicle Crash": "Chute Glace",
    "V-create": "Coup Victoire",
    "Fusion Flare": "Flamme Croix",
    "Fusion Bolt": "Éclair Croix",
    "Flying Press": "Flying Press",
    "Mat Block": "Tatamigaeshi",
    "Belch": "Éructation",
    "Rototiller": "Fertilisation",
    "Sticky Web": "Toile Gluante",
    "Fell Stinger": "Dard Mortel",
    "Phantom Force": "Hantise",
    "Trick-or-Treat": "Halloween",
    "Noble Roar": "Râle Mâle",
    "Ion Deluge": "Déluge Plasmique",
    "Parabolic Charge": "Parabocharge",
    "Forest’s Curse": "Maléfice Sylvain",
    "Petal Blizzard": "Tempête Florale",
    "Freeze-Dry": "Lyophilisation",
    "Disarming Voice": "Voix Enjôleuse",
    "Parting Shot": "Dernier Mot",
    "Topsy-Turvy": "Renversement",
    "Draining Kiss": "Vampibaiser",
    "Crafty Shield": "Vigilance",
    "Flower Shield": "Garde Florale",
    "Grassy Terrain": "Champ Herbu",
    "Misty Terrain": "Champ Brumeux",
    "Electrify": "Électrisation",
    "Play Rough": "Câlinerie",
    "Fairy Wind": "Vent Féérique",
    "Moonblast": "Pouvoir Lunaire",
    "Boomburst": "Bang Sonique",
    "Fairy Lock": "Verrou Enchanté",
    "King’s Shield": "Bouclier Royal",
    "Play Nice": "Camaraderie",
    "Confide": "Confidence",
    "Diamond Storm": "Orage Adamantin",
    "Steam Eruption": "Jet de Vapeur",
    "Hyperspace Hole": "TrouDimensionnel",
    "Water Shuriken": "Sheauriken",
    "Mystical Fire": "Feu Ensorcelé",
    "Spiky Shield": "Pico-Défense",
    "Aromatic Mist": "Brume Capiteuse",
    "Eerie Impulse": "Ondes Étranges",
    "Venom Drench": "Piège de Venin",
    "Powder": "Nuée de Poudre",
    "Geomancy": "Géo-Contrôle",
    "Magnetic Flux": "Magné-Contrôle",
    "Happy Hour": "Étrennes",
    "Electric Terrain": "Champ Électrifié",
    "Dazzling Gleam": "Éclat Magique",
    "Celebrate": "Célébration",
    "Hold Hands": "Mains Jointes",
    "Baby-Doll Eyes": "Regard Touchant",
    "Nuzzle": "Frotte-Frimousse",
    "Hold Back": "Retenue",
    "Infestation": "Harcèlement",
    "Power-Up Punch": "Poing Boost",
    "Oblivion Wing": "Mort’Ailes",
    "Thousand Arrows": "Myria-Flèches",
    "Thousand Waves": "Myria-Vagues",
    "Land’s Wrath": "Force Chtonienne",
    "Light of Ruin": "Lumière du Néant",
    "Origin Pulse": "Onde Originelle",
    "Precipice Blades": "Lame Pangéenne",
    "Dragon Ascent": "Draco-Ascension",
    "Hyperspace Fury": "Furie Dimension",
    "Breakneck Blitz": "Turbo-Charge Bulldozer",
    "All-Out Pummeling": "Combo Hyper-Furie",
    "Supersonic Skystrike": "Piqué Supersonique",
    "Acid Downpour": "Déluge Causti-Toxique",
    "Tectonic Rage": "Éruption Géo-Sismique",
    "Continental Crush": "Apocalypse Gigalithique",
    "Savage Spin-Out": "Cocon Fatal",
    "Never-Ending Nightmare": "Appel des Ombres Éternelles",
    "Corkscrew Crash": "Vrille Maximum",
    "Inferno Overdrive": "Pyro-Explosion Cataclysmique",
    "Hydro Vortex": "Super Tourbillon Abyssal",
    "Bloom Doom": "Pétalexplosion Éblouissante",
    "Gigavolt Havoc": "Fulguro-Lance Gigavolt",
    "Shattered Psyche": "Psycho-Pulvérisation EX",
    "Subzero Slammer": "Laser Cryogénique",
    "Devastating Drake": "Chaos Draconique",
    "Black Hole Eclipse": "Trou Noir des Ombres",
    "Twinkle Tackle": "Impact Choupinova",
    "Catastropika": "Pikachute Foudroyante",
    "Shore Up": "Amass’Sable",
    "First Impression": "Escarmouche",
    "Baneful Bunker": "Blockhaus",
    "Spirit Shackle": "Tisse Ombre",
    "Darkest Lariat": "Dark Lariat",
    "Sparkling Aria": "Aria de l’Écume",
    "Ice Hammer": "Marteau de Glace",
    "Floral Healing": "Soin Floral",
    "High Horsepower": "Cavalerie Lourde",
    "Strength Sap": "Vole-Force",
    "Solar Blade": "Lame Solaire",
    "Leafage": "Feuillage",
    "Spotlight": "Projecteur",
    "Toxic Thread": "Fil Toxique",
    "Laser Focus": "Affilage",
    "Gear Up": "Engrenage",
    "Throat Chop": "Exécu-Son",
    "Pollen Puff": "Boule Pollen",
    "Anchor Shot": "Ancrage",
    "Psychic Terrain": "Champ Psychique",
    "Lunge": "Furie-Bond",
    "Fire Lash": "Fouet de Feu",
    "Power Trip": "Arrogance",
    "Burn Up": "Flamme Ultime",
    "Speed Swap": "Permuvitesse",
    "Smart Strike": "Estocorne",
    "Purify": "Purification",
    "Revelation Dance": "Danse Éveil",
    "Core Enforcer": "Sanction Suprême",
    "Trop Kick": "Botte Sucrette",
    "Instruct": "Sommation",
    "Beak Blast": "Bec-Canon",
    "Clanging Scales": "Vibrécaille",
    "Dragon Hammer": "Draco-Marteau",
    "Brutal Swing": "Centrifugifle",
    "Aurora Veil": "Voile Aurore",
    "Sinister Arrow Raid": "Fureur des Plumes Spectrales",
    "Malicious Moonsault": "Dark Body Press",
    "Oceanic Operetta": "Symphonie des Ondines",
    "Guardian of Alola": "Colère du Gardien d’Alola",
    "Soul-Stealing 7-Star Strike": "Fauche-Âme des Sept Étoiles",
    "Stoked Sparksurfer": "Électro-Surf Survolté",
    "Pulverizing Pancake": "Gare au Ronflex",
    "Extreme Evoboost": "Neuf pour Un",
    "Genesis Supernova": "Supernova Originelle",
    "Shell Trap": "Carapiège",
    "Fleur Cannon": "Canon Floral",
    "Psychic Fangs": "Psycho-Croc",
    "Stomping Tantrum": "Trépignement",
    "Shadow Bone": "Os Ombre",
    "Accelerock": "Vif Roc",
    "Liquidation": "Aqua-Brèche",
    "Prismatic Laser": "Laser Prisme",
    "Spectral Thief": "Clepto-Mânes",
    "Sunsteel Strike": "Choc Météore",
    "Moongeist Beam": "Rayon Spectral",
    "Tearful Look": "Larme à l’Œil",
    "Zing Zap": "Électrikipik",
    "Nature’s Madness": "Ire de la Nature",
    "Multi-Attack": "Coup Varia-Type",
    "10,000,000 Volt Thunderbolt": "Giga-Tonnerre",
    "Mind Blown": "Caboche-Kaboum",
    "Plasma Fists": "Plasma Punch",
    "Photon Geyser": "Photo-Geyser",
    "Light That Burns the Sky": "Apocalypsis Luminis",
    "Searing Sunraze Smash": "Hélio-Choc Dévastateur",
    "Menacing Moonraze Maelstrom": "Rayons Séléno-Explosifs",
    "Let’s Snuggle Forever": "Patati-Patattrape",
    "Splintered Stormshards": "Hurlement des Roches-Lames",
    "Clangorous Soulblaze": "Dracacophonie Flamboyante",
    "Zippy Zap": "Pika-Sprint",
    "Splishy Splash": "Pika-Splash",
    "Floaty Fall": "Pika-Piqué",
    "Pika Papow": "Pika-Fracas",
    "Bouncy Bubble": "Évo-Thalasso",
    "Buzzy Buzz": "Évo-Dynamo",
    "Sizzly Slide": "Évo-Flambo",
    "Glitzy Glow": "Évo-Psycho",
    "Baddy Bad": "Évo-Ténébro",
    "Sappy Seed": "Évo-Écolo",
    "Freezy Frost": "Évo-Congélo",
    "Sparkly Swirl": "Évo-Fabulo",
    "Veevee Volley": "Évo-Chardasso",
    "Double Iron Bash": "Écrous d’Poing",
    "Max Guard": "Gardomax",
    "Dynamax Cannon": "Canon Dynamax",
    "Snipe Shot": "Tir de Précision",
    "Jaw Lock": "Croque Fort",
    "Stuff Cheeks": "Garde-à-Joues",
    "No Retreat": "Ultime Bastion",
    "Tar Shot": "Goudronnage",
    "Magic Powder": "Poudre Magique",
    "Dragon Darts": "Draco-Flèches",
    "Teatime": "Thérémonie",
    "Octolock": "Octoprise",
    "Bolt Beak": "Prise de Bec",
    "Fishious Rend": "Branchicrok",
    "Court Change": "Change-Côté",
    "Max Flare": "Pyromax",
    "Max Flutterby": "Insectomax",
    "Max Lightning": "Fulguromax",
    "Max Strike": "Normalomax",
    "Max Knuckle": "Pugilomax",
    "Max Phantasm": "Spectromax",
    "Max Hailstorm": "Cryomax",
    "Max Ooze": "Toxinomax",
    "Max Geyser": "Hydromax",
    "Max Airstream": "Aéromax",
    "Max Starfall": "Enchantomax",
    "Max Wyrmwind": "Dracomax",
    "Max Mindstorm": "Psychomax",
    "Max Rockfall": "Lithomax",
    "Max Quake": "Sismomax",
    "Max Darkness": "Sinistromax",
    "Max Overgrowth": "Phytomax",
    "Max Steelspike": "Métallomax",
    "Clangorous Soul": "Dracacophonie",
    "Body Press": "Big Splash",
    "Decorate": "Nappage",
    "Drum Beating": "Tambour Battant",
    "Snap Trap": "Troquenard",
    "Pyro Ball": "Ballon Brûlant",
    "Behemoth Blade": "Gladius Maximus",
    "Behemoth Bash": "Aegis Maxima",
    "Aura Wheel": "Roue Libre",
    "Breaking Swipe": "Abattage",
    "Branch Poke": "Tapotige",
    "Overdrive": "Overdrive",
    "Apple Acid": "Acide Malique",
    "Grav Apple": "Force G",
    "Spirit Break": "Choc Émotionnel",
    "Strange Steam": "Vapeur Féérique",
    "Life Dew": "Fontaine de Vie",
    "Obstruct": "Blocage",
    "False Surrender": "Fourbette",
    "Meteor Assault": "Joute Astrale",
    "Eternabeam": "Laser Infinimax",
    "Steel Beam": "Métalaser",
    "Expanding Force": "Vaste Pouvoir",
    "Steel Roller": "Métalliroue",
    "Scale Shot": "Rafale Écailles",
    "Meteor Beam": "Laser Météore",
    "Shell Side Arm": "Kokiyarme",
    "Misty Explosion": "Explo-Brume",
    "Grassy Glide": "Gliss’Herbe",
    "Rising Voltage": "Monte-Tension",
    "Terrain Pulse": "Champlification",
    "Skitter Smack": "Ravage Rampant",
    "Burning Jealousy": "Feu Envieux",
    "Lash Out": "Cent Rancunes",
    "Poltergeist": "Esprit Frappeur",
    "Corrosive Gas": "Gaz Corrosif",
    "Coaching": "Coaching",
    "Flip Turn": "Eau Revoir",
    "Triple Axel": "Triple Axel",
    "Dual Wingbeat": "Double Volée",
    "Scorching Sands": "Sable Ardent",
    "Jungle Healing": "Selve Salvatrice",
    "Wicked Blow": "Poing Obscur",
    "Surging Strikes": "Torrent de Coups",
    "Thunder Cage": "Voltageôle",
    "Dragon Energy": "Draco-Énergie",
    "Freezing Glare": "Regard Glaçant",
    "Fiery Wrath": "Fureur Ardente",
    "Thunderous Kick": "Coup Fulgurant",
    "Glacial Lance": "Lance de Glace",
    "Astral Barrage": "Éclat Spectral",
    "Eerie Spell": "Sort Sinistre",
    "Dire Claw": "Griffes Funestes",
    "Psyshield Bash": "Sprint Bouclier",
    "Power Shift": "Échange Force",
    "Stone Axe": "Hache de Pierre",
    "Springtide Storm": "Typhon Passionné",
    "Mystical Power": "Force Mystique",
    "Raging Fury": "Grand Courroux",
    "Wave Crash": "Aquatacle",
    "Chloroblast": "Herblast",
    "Mountain Gale": "Bise Glaciaire",
    "Victory Dance": "Danse Victoire",
    "Headlong Rush": "Assaut Frontal",
    "Barb Barrage": "Multitoxik",
    "Esper Wing": "Ailes Psycho",
    "Bitter Malice": "Cœur de Rancœur",
    "Shelter": "Mur Fumigène",
    "Triple Arrows": "Triple Flèche",
    "Infernal Parade": "Cortège Funèbre",
    "Ceaseless Edge": "Vagues à Lames",
    "Bleakwind Storm": "Typhon Hivernal",
    "Wildbolt Storm": "Typhon Fulgurant",
    "Sandsear Storm": "Typhon Pyrosable",
    "Lunar Blessing": "Prière Lunaire",
    "Take Heart": "Extravaillance",
    "Tera Blast": "Téra Explosion",
    "Silk Trap": "Piège de Fil",
    "Axe Kick": "Talon-Marteau",
    "Last Respects": "Hommage Posthume",
    "Lumina Crash": "Lumino-Impact",
    "Order Up": "Plat du Jour",
    "Jet Punch": "Poing Sonique",
    "Spicy Extract": "Habanerage",
    "Spin Out": "Dérapage",
    "Population Bomb": "Prolifération",
    "Ice Spinner": "Cryo-Pirouette",
    "Glaive Rush": "Charge Glaive",
    "Revival Blessing": "Second Souffle",
    "Salt Cure": "Salaison",
    "Triple Dive": "Triple Plongeon",
    "Mortal Spin": "Toupie Éclat",
    "Doodle": "Décalquage",
    "Fillet Away": "Décharnement",
    "Kowtow Cleave": "Génusection",
    "Flower Trick": "Magie Florale",
    "Torch Song": "Chant Flamboyant",
    "Aqua Step": "Danse Aquatique",
    "Raging Bull": "Taurogne",
    "Make It Rain": "Ruée d'Or",
    "Psyblade": "Lame Psychique",
    "Hydro Steam": "Hydrovapeur",
    "Ruination": "Cataclysme",
    "Collision Course": "Nitro Crash",
    "Electro Drift": "Turbo Volt",
    "Shed Tail": "Queulonage",
    "Chilly Reception": "Neigeux de Mots",
    "Tidy Up": "Grand Nettoyage",
    "Snowscape": "Chute de Neige",
    "Pounce": "Bond",
    "Trailblaze": "Désherbaffe",
    "Chilling Water": "Douche Froide",
    "Hyper Drill": "Hyperceuse",
    "Twin Beam": "Double Laser",
    "Rage Fist": "Poing de Colère",
    "Armor Cannon": "Canon Blindé",
    "Bitter Blade": "Lame en Peine",
    "Double Shock": "Double Décharge",
    "Gigaton Hammer": "Marteau Mastoc",
    "Comeuppance": "Vindicte",
    "Aqua Cutter": "Tranch'Aqua",
    "Blazing Torque": "Crash Brûlant",
    "Wicked Torque": "Crash Obscur",
    "Noxious Torque": "Crash Toxique",
    "Combat Torque": "Crash Musclé",
    "Magical Torque": "Crash Magique",
    "Blood Moon": "Lune Rouge",
    "Matcha Gotcha": "Mortier Matcha",
    "Syrup Bomb": "Bombe au Sirop",
    "Ivy Cudgel": "Massue Liane",
    "Electro Shot": "Fulgurayon",
    "Tera Starstorm": "Pluie Térastrale",
    "Fickle Beam": "Laser Hasard",
    "Burning Bulwark": "Rempart Brûlant",
    "Thunderclap": "Vif Éclair",
    "Mighty Cleave": "Lame Puissante",
    "Tachyon Cutter": "Lame Tachyonique",
    "Hard Press": "Pression Extrême",
    "Dragon Cheer": "Cri Draconique",
    "Alluring Voice": "Voix Envoûtante",
    "Temper Flare": "Indignition",
    "Supercell Slam": "Volt Assaut",
    "Psychic Noise": "Dissonance Psy",
    "Upper Hand": "Prio-Parade",
    "Malignant Chain": "Chaîne Malsaine",
    "Shadow Rush": "Charge Noire",
    "Shadow Blast": "Aéro Noir",
    "Shadow Blitz": "Assaut Noir",
    "Shadow Bolt": "Éclair Noir",
    "Shadow Break": "Bélier Noir",
    "Shadow Chill": "Froid Noir",
    "Shadow End": "Retour Noir",
    "Shadow Fire": "Ardeur Noir",
    "Shadow Rave": "Rage Noire",
    "Shadow Storm": "Typhon Noir",
    "Shadow Wave": "Ondo Noire",
    "Shadow Down": "Souffle Noir",
    "Shadow Half": "Chute Noire",
    "Shadow Hold": "Blocage Noir",
    "Shadow Mist": "Brume Noire",
    "Shadow Panic": "Folie Noire",
    "Shadow Shed": "Percée Noire",
    "Shadow Sky": "Ciel Noir"
}
